
import ButtonModule from "@/components/buttons";
import CardModule from "@/components/card";
import FormModule from "@/components/form";
import TableModule from "@/components/table";
import UploadFile from "@/components/upload-file";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableModule />
      <div className="" style={{ margin: "0px", display: "flex" ,justifyContent:"space-between"}}>
        <div style={{ flexBasis: "33%" }}>
          <UploadFile />
          <br />
          <ButtonModule />
        </div>
        <div style={{ flexBasis: "33%" }}>
          <CardModule />
        </div>
        <div style={{ flexBasis: "40%" }}>
          <FormModule />
        </div>
      </div>
    </>
  );
}
